env:
  matrix:
    - DJANGO=1.6
    - DJANGO=1.7
language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install django==${DJANGO}
  - "pip install psycopg2 django_hstore"
  - "pip install ."
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database daffodil_hstore_test;' -U postgres
  - psql daffodil_hstore_test -c 'CREATE EXTENSION IF NOT EXISTS hstore;' -U postgres
script: python test/test.py
