env:
  matrix:
    - DJANGO=1.9
    - DJANGO=1.10
    - DJANGO=1.11
language: python
python:
  - "3.6"
install:
  - pip install django==${DJANGO}
  - "pip install psycopg2 git+https://github.com/mediapredict/django-hstore.git@v1.4.3 future==0.16.0"
  - "pip install ."
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database daffodil_hstore_test;' -U postgres
  - psql daffodil_hstore_test -c 'CREATE EXTENSION IF NOT EXISTS hstore;' -U postgres
script: python test/tests.py
