language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install ."
  - "pip install django==1.6 psycopg2 django_hstore"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create extension hstore;' -U postgres
script: python test/test.py
